import { initiateDeveloperControlledWalletsClient } from "@circle-fin/developer-controlled-wallets";
import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";

dotenv.config();

async function main() {
  const apiKey = process.env.CIRCLE_API_KEY;
  const entitySecret = process.env.CIRCLE_ENTITY_SECRET;

  if (!apiKey || !entitySecret) {
    throw new Error("Missing CIRCLE_API_KEY or CIRCLE_ENTITY_SECRET in .env");
  }

  // 1. Initialize Client
  const client = initiateDeveloperControlledWalletsClient({
    apiKey,
    entitySecret,
  });

  console.log("🚀 Initializing Circle Developer-Controlled Infrastructure...");

  // 2. Create Wallet Set
  console.log("Creating Wallet Set for AgentStack...");
  const walletSetResponse = await client.createWalletSet({
    name: "AgentStack Multi-Agent Set",
  });

  const walletSetId = walletSetResponse.data?.walletSet?.id;
  if (!walletSetId) throw new Error("Failed to create Wallet Set");
  console.log(`✅ Wallet Set Created: ${walletSetId}`);

  // 3. Create 3 Wallets on Arc (Orchestrator, Market, Sentiment)
  console.log("Creating Agent Wallets on ARC-TESTNET...");
  const walletResponse = await client.createWallets({
    blockchains: ["ARC-TESTNET"],
    count: 3,
    walletSetId: walletSetId,
    accountType: "EOA",
  });

  const wallets = walletResponse.data?.wallets;
  if (!wallets || wallets.length < 3) throw new Error("Failed to create all 3 Wallets");

  const orchestrator = wallets[0];
  const marketWorker = wallets[1];
  const sentimentWorker = wallets[2];

  console.log("\n✨ WALLETS CREATED SUCCESSFULLY ✨");
  console.log("--------------------------------------------------");
  console.log(`Orchestrator:     ${orchestrator.address} (ID: ${orchestrator.id})`);
  console.log(`Market Worker:    ${marketWorker.address} (ID: ${marketWorker.id})`);
  console.log(`Sentiment Worker: ${sentimentWorker.address} (ID: ${sentimentWorker.id})`);
  console.log("--------------------------------------------------");

  // 4. Update .env automatically
  const envPath = path.join(process.cwd(), ".env");
  let envContent = "";
  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, "utf8");
  } else {
    const examplePath = path.join(process.cwd(), ".env.example");
    if (fs.existsSync(examplePath)) {
      envContent = fs.readFileSync(examplePath, "utf8");
    }
  }
  
  const newEnvVars = `
# --- Generated by init script ---
ORCHESTRATOR_WALLET_ID="${orchestrator.id}"
ORCHESTRATOR_ADDRESS="${orchestrator.address}"
WORKER_MARKET_WALLET_ID="${marketWorker.id}"
WORKER_MARKET_ADDRESS="${marketWorker.address}"
WORKER_SENTIMENT_WALLET_ID="${sentimentWorker.id}"
WORKER_SENTIMENT_ADDRESS="${sentimentWorker.address}"
`;

  fs.writeFileSync(envPath, envContent + newEnvVars);
  console.log("\n✅ .env file updated with all agent wallet details.");
  
  console.log("\n🔥 NEXT STEP:");
  console.log(`Fund the Orchestrator address at https://faucet.circle.com: ${orchestrator.address}`);
}

main().catch((err) => {
  console.error("❌ Error:", err.message || err);
  process.exit(1);
});
