import { initiateDeveloperControlledWalletsClient } from "@circle-fin/developer-controlled-wallets";
import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";

dotenv.config();

async function main() {
  const apiKey = process.env.CIRCLE_API_KEY;
  const entitySecret = process.env.CIRCLE_ENTITY_SECRET;

  if (!apiKey || !entitySecret) {
    throw new Error("Missing CIRCLE_API_KEY or CIRCLE_ENTITY_SECRET in .env");
  }

  // 1. Initialize Client
  const client = initiateDeveloperControlledWalletsClient({
    apiKey,
    entitySecret,
  });

  console.log("🚀 Initializing Circle Developer-Controlled Infrastructure...");

  // 2. Create Wallet Set
  console.log("Creating Wallet Set for AgentStack...");
  const walletSetResponse = await client.createWalletSet({
    name: "AgentStack Orchestrator Set",
  });

  const walletSetId = walletSetResponse.data?.walletSet?.id;
  if (!walletSetId) throw new Error("Failed to create Wallet Set");
  console.log(`✅ Wallet Set Created: ${walletSetId}`);

  // 3. Create Orchestrator Wallet on Arc
  console.log("Creating Orchestrator Wallet on ARC-TESTNET...");
  const walletResponse = await client.createWallets({
    blockchains: ["ARC-TESTNET"],
    count: 1,
    walletSetId: walletSetId,
    accountType: "EOA",
  });

  const wallet = walletResponse.data?.wallets?.[0];
  if (!wallet) throw new Error("Failed to create Wallet");

  console.log("\n✨ WALLET CREATED SUCCESSFULLY ✨");
  console.log("--------------------------------------------------");
  console.log(`Wallet ID:      ${wallet.id}`);
  console.log(`Public Address: ${wallet.address}`);
  console.log(`Blockchain:     ${wallet.blockchain}`);
  console.log("--------------------------------------------------");

  // 4. Update .env automatically
  const envPath = path.join(process.cwd(), ".env");
  const envContent = fs.readFileSync(envPath, "utf8");
  
  const updatedEnv = envContent 
    + `\n# --- Generated by init script ---`
    + `\nORCHESTRATOR_WALLET_ID="${wallet.id}"`
    + `\nORCHESTRATOR_ADDRESS="${wallet.address}"\n`;

  fs.writeFileSync(envPath, updatedEnv);
  console.log("\n✅ .env file updated with new wallet details.");
  
  console.log("\n🔥 NEXT STEP:");
  console.log(`Go to https://faucet.circle.com and fund this address: ${wallet.address}`);
}

main().catch((err) => {
  console.error("❌ Error:", err.message || err);
  process.exit(1);
});
